# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGrfKo8vW6lLTkydrKiCWekSsLZu0nCK
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from collections import Counter

# Load the Fashion-MNIST Dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

# =============================================================================
# Dataset Summary

print("Dataset Summary")

print(f"Training Images Shape : {x_train.shape}")
print(f"Training Labels Shape : {y_train.shape}")

print(f"Testing Images Shape  : {x_test.shape}")
print(f"Testing Labels Shape  : {y_test.shape}")

print(f"\nImage Dimensions      : {x_train.shape[1]} x {x_train.shape[2]} pixels")

print(f"Number of Classes     : {len(np.unique(y_train))}")

print(f"Training Samples      : {len(x_train)}")
print(f"Testing Samples       : {len(x_test)}")

class_names = [
    "T-Shirt/Top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle Boot"
]

# Display Sample Images
fig, axes = plt.subplots(2, 5, figsize=(12, 5))

for index, axis in enumerate(axes.flat):
    axis.imshow(x_train[index], cmap="gray")
    axis.set_title(class_names[y_train[index]], fontsize=10)
    axis.axis("off")

plt.suptitle("Sample Images from Fashion-MNIST Dataset",
             fontsize=14,
             fontweight="bold")

plt.tight_layout()

plt.savefig(
    "sample_images.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# Class Distribution

class_counts = Counter(y_train)

labels = [class_names[i] for i in range(len(class_names))]
counts = [class_counts[i] for i in range(len(class_names))]

plt.figure(figsize=(10, 5))

plt.bar(labels, counts)

plt.title("Class Distribution of Fashion-MNIST Training Dataset",
          fontsize=14,
          fontweight="bold")

plt.xlabel("Class")
plt.ylabel("Number of Images")

plt.xticks(rotation=30, ha="right")

plt.grid(axis="y", linestyle="--", alpha=0.4)

plt.tight_layout()

plt.savefig(
    "class_distribution.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# Task 2: Data Preprocessing
from tensorflow.keras.utils import to_categorical
print("DATA PREPROCESSING")
# Display Original Tensor Shapes
print("\nOriginal Dataset Shapes")
print(f"x_train : {x_train.shape}")
print(f"y_train : {y_train.shape}")
print(f"x_test  : {x_test.shape}")
print(f"y_test  : {y_test.shape}")

# Flatten Images (28 × 28 → 784)
x_train_flat = x_train.reshape(x_train.shape[0], -1)
x_test_flat = x_test.reshape(x_test.shape[0], -1)
print("\nAfter Flattening")
print(f"x_train_flat : {x_train_flat.shape}")
print(f"x_test_flat  : {x_test_flat.shape}")

# Normalize Pixel Value
x_train_flat = x_train_flat.astype("float32") / 255.0
x_test_flat = x_test_flat.astype("float32") / 255.0
print("\nPixel Value Range")
print(f"Minimum Pixel Value : {x_train_flat.min():.2f}")
print(f"Maximum Pixel Value : {x_train_flat.max():.2f}")

# One-Hot Encode Labels
y_train_encoded = to_categorical(y_train, num_classes=10)
y_test_encoded = to_categorical(y_test, num_classes=10)

print("\nAfter One-Hot Encoding")
print(f"y_train_encoded : {y_train_encoded.shape}")
print(f"y_test_encoded  : {y_test_encoded.shape}")

# Display Sample After Preprocessing
print("\nSample Flattened Image (First 20 Values)")
print(x_train_flat[0][:20])
print("\nCorresponding One-Hot Label")
print(y_train_encoded[0])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# Build the Multi-Layer Perceptron (MLP)
mlp_model = Sequential(
    [
        Dense(
            units=128,
            activation="relu",
            input_shape=(784,),
            name="Hidden_Layer_1"
        ),

        Dense(
            units=64,
            activation="relu",
            name="Hidden_Layer_2"
        ),

        Dense(
            units=10,
            activation="softmax",
            name="Output_Layer"
        )
    ],
    name="Fashion_MNIST_MLP"
)

# Display Model Architecture
print("MODEL ARCHITECTURE")
mlp_model.summary()

from tensorflow.keras.optimizers import Adam
# Compile the MLP Model
mlp_model.compile(
    optimizer=Adam(),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

import time
start_time = time.perf_counter()
history = mlp_model.fit(
    x=x_train_flat,
    y=y_train_encoded,
    validation_split=0.20,
    epochs=20,
    batch_size=32,
    shuffle=True,
    verbose=1
)

end_time = time.perf_counter()

baseline_training_time = end_time - start_time

print(f"\nBaseline Training Time : {baseline_training_time:.2f} seconds")

print("\nTraining Completed Successfully")
print(f"Final Training Accuracy   : {history.history['accuracy'][-1]:.4f}")
print(f"Final Validation Accuracy : {history.history['val_accuracy'][-1]:.4f}")

print(f"Final Training Loss       : {history.history['loss'][-1]:.4f}")
print(f"Final Validation Loss     : {history.history['val_loss'][-1]:.4f}")

print(f"Training Time             : {baseline_training_time:.2f} seconds")

test_loss, test_accuracy = mlp_model.evaluate(
    x_test_flat,
    y_test_encoded,
    verbose=0
)
print("MODEL PERFORMANCE")
print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy:.4f}")

# Predict Class Labels
predicted_probabilities = mlp_model.predict(x_test_flat, verbose=0)

predicted_labels = np.argmax(predicted_probabilities, axis=1)

true_labels = np.argmax(y_test_encoded, axis=1)

# Performance Metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
accuracy = accuracy_score(true_labels, predicted_labels)
precision = precision_score(
    true_labels,
    predicted_labels,
    average="weighted"
)
recall = recall_score(
    true_labels,
    predicted_labels,
    average="weighted"
)
f1 = f1_score(
    true_labels,
    predicted_labels,
    average="weighted"
)
print("\nClassification Metrics")
print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-Score  : {f1:.4f}")

from sklearn.metrics import classification_report
print("\nClassification Report")
print("-" * 60)

print(
    classification_report(
        true_labels,
        predicted_labels,
        target_names=class_names
    )
)

# Confusion Matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(
    true_labels,
    predicted_labels
)
print("\nConfusion Matrix")
print(conf_matrix)

# Confusion Matrix Visualization

plt.figure(figsize=(9, 8))

plt.imshow(conf_matrix, cmap="Blues")

plt.title(
    "Confusion Matrix",
    fontsize=14,
    fontweight="bold"
)

plt.colorbar()

tick_marks = np.arange(len(class_names))

plt.xticks(
    tick_marks,
    class_names,
    rotation=45,
    ha="right"
)

plt.yticks(
    tick_marks,
    class_names
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")

for i in range(conf_matrix.shape[0]):
    for j in range(conf_matrix.shape[1]):
        plt.text(
            j,
            i,
            conf_matrix[i, j],
            ha="center",
            va="center",
            fontsize=8,
            color="black"
        )

plt.tight_layout()

plt.savefig(
    "confusion_matrix.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# Training Accuracy vs Epoch
plt.figure(figsize=(8, 5))
plt.plot(
    history.history["accuracy"],
    linewidth=2,
    label="Training Accuracy"
)
plt.title(
    "Training Accuracy vs Epoch",
    fontsize=14,
    fontweight="bold"
)
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.tight_layout()
plt.savefig(
    "training_accuracy.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

# Validation Accuracy vs Epoch
plt.figure(figsize=(8,5))
plt.plot(
    history.history["val_accuracy"],
    linewidth=2,
    label="Validation Accuracy"
)
plt.title(
    "Validation Accuracy vs Epoch",
    fontsize=14,
    fontweight="bold"
)
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.tight_layout()
plt.savefig(
    "validation_accuracy.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

# Training Loss vs Epoch
plt.figure(figsize=(8,5))
plt.plot(
    history.history["loss"],
    linewidth=2,
    label="Training Loss"
)
plt.title(
    "Training Loss vs Epoch",
    fontsize=14,
    fontweight="bold"
)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.tight_layout()
plt.savefig(
    "training_loss.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

# Validation Loss vs Epoch
plt.figure(figsize=(8,5))
plt.plot(
    history.history["val_loss"],
    linewidth=2,
    label="Validation Loss"
)
plt.title(
    "Validation Loss vs Epoch",
    fontsize=14,
    fontweight="bold"
)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True, linestyle="--", alpha=0.4)
plt.legend()
plt.tight_layout()
plt.savefig(
    "validation_loss.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)
plt.show()

!pip install scikit-learn==1.5.2
!pip install scikeras==0.13.0

# =============================================================================
# Task 6 : Hyperparameter Optimization
# =============================================================================

import time
import numpy as np
import pandas as pd

from sklearn.model_selection import RandomizedSearchCV

from scikeras.wrappers import KerasClassifier

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.optimizers import RMSprop

# =============================================================================
# Model Builder Function
# =============================================================================

def build_model(hidden_layers=2,
                hidden_neurons=128,
                activation="relu",
                optimizer="adam",
                learning_rate=0.001,
                dropout_rate=0.0):

    model = Sequential()

    model.add(Input(shape=(784,)))

    for _ in range(hidden_layers):

        model.add(
            Dense(
                hidden_neurons,
                activation=activation
            )
        )

        if dropout_rate > 0:
            model.add(Dropout(dropout_rate))

    model.add(
        Dense(
            10,
            activation="softmax"
        )
    )

    if optimizer == "adam":
        opt = Adam(learning_rate=learning_rate)

    elif optimizer == "sgd":
        opt = SGD(learning_rate=learning_rate)

    else:
        opt = RMSprop(learning_rate=learning_rate)

    model.compile(
        optimizer=opt,
        loss="categorical_crossentropy",
        metrics=["accuracy"]
    )

    return model

keras_classifier = KerasClassifier(
    model=build_model,
    verbose=0
)

param_distributions = {

    "model__hidden_layers":[1,2],

    "model__hidden_neurons":[64,128],

    "model__activation":[
        "relu",
        "tanh"
    ],

    "model__optimizer":[
        "adam",
        "rmsprop"
    ],

    "model__learning_rate":[
        0.001,
        0.01
    ],

    "model__dropout_rate":[
        0.0,
        0.2
    ],

    "batch_size":[
        32
    ],

    "epochs":[
        10
    ]

}

random_search = RandomizedSearchCV(

    estimator=keras_classifier,

    param_distributions=param_distributions,

    n_iter=5,

    cv=3,

    scoring="accuracy",

    random_state=42,

    n_jobs=1
)

search_start = time.perf_counter()

random_search.fit(
    x_train_flat,
    y_train_encoded
)

search_end = time.perf_counter()

hyperparameter_search_time = search_end - search_start

print("="*60)
print("BEST HYPERPARAMETERS")
print("="*60)

for key,value in random_search.best_params_.items():
    print(f"{key:30} : {value}")

print("\nCross Validation Accuracy :",
      round(random_search.best_score_,4))

print("Search Time :",
      round(hyperparameter_search_time,2),
      "seconds")

optimized_model = random_search.best_estimator_

training_start = time.perf_counter()

optimized_model.fit(
    x_train_flat,
    y_train_encoded
)

training_end = time.perf_counter()

optimized_training_time = (
    training_end -
    training_start
)

optimized_loss, optimized_accuracy = optimized_model.model_.evaluate(

    x_test_flat,

    y_test_encoded,

    verbose=0
)

optimized_predictions = optimized_model.predict(
    x_test_flat
)

optimized_predictions = np.argmax(
    optimized_predictions,
    axis=1
)

true_labels = np.argmax(
    y_test_encoded,
    axis=1
)

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

optimized_accuracy = accuracy_score(
    true_labels,
    optimized_predictions
)

optimized_precision = precision_score(
    true_labels,
    optimized_predictions,
    average="weighted"
)

optimized_recall = recall_score(
    true_labels,
    optimized_predictions,
    average="weighted"
)

optimized_f1 = f1_score(
    true_labels,
    optimized_predictions,
    average="weighted"
)

print("="*60)
print("OPTIMIZED MODEL RESULTS")
print("="*60)

print(f"Accuracy        : {optimized_accuracy:.4f}")

print(f"Precision       : {optimized_precision:.4f}")

print(f"Recall          : {optimized_recall:.4f}")

print(f"F1 Score        : {optimized_f1:.4f}")

print(f"Training Time   : {optimized_training_time:.2f} seconds")

print(random_search.best_params_)
print(random_search.best_score_)

est_model = random_search.best_estimator_

optimized_train_start = time.perf_counter()

est_model.fit(
    x_train_flat,
    y_train_encoded
)

optimized_train_end = time.perf_counter()

optimized_training_time = (
    optimized_train_end - optimized_train_start
)

print(f"Optimized Model Training Time : {optimized_training_time:.2f} seconds")

optimized_loss, optimized_accuracy = optimized_model.model_.evaluate(
    x_test_flat,
    y_test_encoded,
    verbose=0
)

# =============================================================================
# Evaluate the Optimized Model
# =============================================================================

optimized_loss, optimized_test_accuracy = est_model.model_.evaluate(
    x_test_flat,
    y_test_encoded,
    verbose=0
)

print("=" * 60)
print("OPTIMIZED MODEL PERFORMANCE")
print("=" * 60)

print(f"Test Loss     : {optimized_loss:.4f}")
print(f"Test Accuracy : {optimized_test_accuracy:.4f}")

# =============================================================================
# Predict Test Labels
# =============================================================================

predicted_probabilities = est_model.model_.predict(
    x_test_flat,
    verbose=0
)

predicted_labels = np.argmax(
    predicted_probabilities,
    axis=1
)

true_labels = np.argmax(
    y_test_encoded,
    axis=1
)

# =============================================================================
# Performance Metrics
# =============================================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

optimized_accuracy = accuracy_score(
    true_labels,
    predicted_labels
)

optimized_precision = precision_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

optimized_recall = recall_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

optimized_f1 = f1_score(
    true_labels,
    predicted_labels,
    average="weighted"
)

print("\nClassification Metrics")
print("-" * 40)

print(f"Accuracy  : {optimized_accuracy:.4f}")
print(f"Precision : {optimized_precision:.4f}")
print(f"Recall    : {optimized_recall:.4f}")
print(f"F1-Score  : {optimized_f1:.4f}")

# =============================================================================
# Classification Report
# =============================================================================

from sklearn.metrics import classification_report

print("\nClassification Report")
print("-" * 60)

print(
    classification_report(
        true_labels,
        predicted_labels,
        target_names=class_names
    )
)

# =============================================================================
# Confusion Matrix
# =============================================================================

from sklearn.metrics import confusion_matrix

optimized_confusion_matrix = confusion_matrix(
    true_labels,
    predicted_labels
)

print("\nConfusion Matrix")
print("-" * 60)

print(optimized_confusion_matrix)

# =============================================================================
# Confusion Matrix Plot
# =============================================================================

plt.figure(figsize=(9,8))

plt.imshow(
    optimized_confusion_matrix,
    cmap="Blues"
)

plt.title(
    "Optimized Model Confusion Matrix",
    fontsize=14,
    fontweight="bold"
)

plt.colorbar()

tick_marks = np.arange(len(class_names))

plt.xticks(
    tick_marks,
    class_names,
    rotation=45,
    ha="right"
)

plt.yticks(
    tick_marks,
    class_names
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")

for i in range(optimized_confusion_matrix.shape[0]):
    for j in range(optimized_confusion_matrix.shape[1]):
        plt.text(
            j,
            i,
            optimized_confusion_matrix[i, j],
            ha="center",
            va="center",
            fontsize=8
        )

plt.tight_layout()

plt.savefig(
    "optimized_confusion_matrix.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# =============================================================================
# Hyperparameter Search Results
# =============================================================================

import pandas as pd
import matplotlib.pyplot as plt

search_results = pd.DataFrame(random_search.cv_results_)

search_results = search_results.sort_values(
    by="mean_test_score",
    ascending=False
).reset_index(drop=True)

plt.figure(figsize=(10, 6))

plt.plot(
    range(1, len(search_results) + 1),
    search_results["mean_test_score"],
    marker="o",
    linewidth=2
)

plt.title(
    "Hyperparameter Search Results",
    fontsize=14,
    fontweight="bold"
)

plt.xlabel("Hyperparameter Combination")
plt.ylabel("Mean Cross-Validation Accuracy")

plt.xticks(range(1, len(search_results) + 1))

plt.grid(True, linestyle="--", alpha=0.5)

plt.tight_layout()

plt.savefig(
    "hyperparameter_search_results.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

# =============================================================================
# Best Model Accuracy Comparison
# =============================================================================

model_names = [
    "Baseline MLP",
    "Optimized MLP"
]

accuracy_values = [
    accuracy,
    optimized_accuracy
]

plt.figure(figsize=(7,5))

bars = plt.bar(
    model_names,
    accuracy_values
)

plt.title(
    "Best Model Accuracy Comparison",
    fontsize=14,
    fontweight="bold"
)

plt.ylabel("Testing Accuracy")

plt.ylim(0.80, 1.00)

for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.003,
        f"{height:.4f}",
        ha="center",
        fontsize=10
    )

plt.tight_layout()

plt.savefig(
    "best_model_accuracy_comparison.eps",
    format="eps",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

print("Hidden Layers          :", random_search.best_params_["model__hidden_layers"])
print("Hidden Neurons         :", random_search.best_params_["model__hidden_neurons"])
print("Learning Rate          :", random_search.best_params_["model__learning_rate"])
print("Batch Size             :", random_search.best_params_["batch_size"])
print("Optimizer              :", random_search.best_params_["model__optimizer"])
print("Activation Function    :", random_search.best_params_["model__activation"])
print("Epochs                 :", random_search.best_params_["epochs"])
print("Dropout                :", random_search.best_params_["model__dropout_rate"])
print("Cross-validation Acc.  :", random_search.best_score_)
print("Testing Accuracy       :", optimized_accuracy)

